export const uiText = {
  English: {
    selectBook: "Select Book",
    selectChapter: "Select Chapter",
    search: "Search",
    bibleNavigation: "Bible Navigation",
    selectBookOrChapter: "Select a book or chapter to read",
    commentary: "Commentary",
    share: "Share",
    shareVerse: "Share this verse",
    copyLink: "Copy link",
    linkCopied: "Link copied!",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    chapters: "Chapters",
    books: "Books",
    study: "Study",
    questions: "Questions",
    sections: "Sections",
    onThisPage: "On this page",
    introduction: "Introduction",
    oldTestament: "Old Testament",
    newTestament: "New Testament",
  },
  Spanish: {
    selectBook: "Seleccionar Libro",
    selectChapter: "Seleccionar Capítulo",
    search: "Buscar",
    bibleNavigation: "Navegación de la Biblia",
    selectBookOrChapter: "Seleccione un libro o capítulo para leer",
    commentary: "Comentario",
    share: "Compartir",
    shareVerse: "Compartir este versículo",
    copyLink: "Copiar enlace",
    linkCopied: "¡Enlace copiado!",
    expandSidebar: "Expandir barra lateral",
    collapseSidebar: "Contraer barra lateral",
    chapters: "Capítulos",
    books: "Libros",
    study: "Estudio",
    questions: "Preguntas",
    sections: "Secciones",
    onThisPage: "En esta página",
    introduction: "Introducción",
    oldTestament: "Antiguo Testamento",
    newTestament: "Nuevo Testamento",
  },
  Arabic: {
    selectBook: "اختر الكتاب",
    selectChapter: "اختر الفصل",
    search: "بحث",
    bibleNavigation: "تنقل الكتاب المقدس",
    selectBookOrChapter: "اختر كتابًا أو فصلًا للقراءة",
    commentary: "تعليق",
    share: "شارك",
    shareVerse: "شارك هذه الآية",
    copyLink: "نسخ الرابط",
    linkCopied: "تم نسخ الرابط!",
    expandSidebar: "توسيع الشريط الجانبي",
    collapseSidebar: "طي الشريط الجانبي",
    chapters: "الاصحاحات",
    books: "الكتب",
    study: "دراسة",
    questions: "أسئلة",
    sections: "أقسام",
    onThisPage: "في هذه الصفحة",
    introduction: "مقدمة",
    oldTestament: "العهد القديم",
    newTestament: "العهد الجديد",
  },
};
