export const uiText = {
  English: {
    selectBook: "Select Book",
    selectChapter: "Select Chapter",
    search: "Search",
    bibleNavigation: "Bible Navigation",
    selectBookOrChapter: "Select a book or chapter to read",
    commentary: "Commentary",
    share: "Share",
    shareVerse: "Share this verse",
    copyLink: "Copy link",
    linkCopied: "Link copied!",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    chapters: "Chapters",
    books: "Books",
    study: "Study",
    questions: "Questions",
    sections: "Sections",
    onThisPage: "On this page",
    introduction: "Introduction",
    oldTestament: "Old Testament",
    newTestament: "New Testament",
    home: "Home",
    bookIntroduction: "Book Introduction",
    overview: "Overview",
    currentEdition: "Current Edition",
    translationLibrary: "Translation Library",
    browseScripture: "Browse Scripture by",
    testamentBookChapter: "testament, book, and chapter",
    translationLibraryDesc: "Move from translation context into a specific book without leaving the study atmosphere.",
    published: "Published",
    enterTheText: "Enter the text.",
    majorMovementsIn: "Major movements in",
    startWithIntroduction: "Start with the introduction or enter the book chapter by chapter.",
    fullChapterGridContinues: "The full chapter grid continues below.",
    chapterReading: "Chapter Reading",
    chapterReadingDesc: "Read the text, surface important verses, and move through commentary without leaving the chapter.",
    previousChapter: "Previous chapter",
    nextChapter: "Next chapter",
    showSidebar: "Show sidebar",
    menu: "Menu",
    sectionLabel: "Section",
    chapterLabel: "Chapter",
    ofLabel: "of",
    sideBySide: "Side by side",
    verseByVerse: "Verse by verse",
    askBibleQuestion: "Ask a Bible question",
    navigationMenu: "Navigation Menu",
    holyBibleReader: "Holy Bible Reader",
    illuminatedStudy: "Illuminated Study",
    library: "Library",
    ask: "Ask",
    scriptureContextReverence: "Scripture, Context, Reverence",
    homeHeroTitleStart: "Read the Bible in a",
    homeHeroTitleAccent: "modern study room",
    homeHeroTitleEnd: "not a utility dashboard.",
    homeHeroBody: "Move from book introductions to chapter reading, side-by-side study, guided questions, and multilingual access in one unified experience.",
    openStudyLibrary: "Open the Study Library",
    readingPathsTitle: "Reading Paths",
    readingPaths: [
      {
        title: "Begin with Genesis",
        description: "Enter the story world of Scripture with creation, covenant, and the shape of redemption.",
        href: "/asv/genesis",
      },
      {
        title: "Meet Christ in John",
        description: "Start with a Gospel that lingers on identity, signs, and the invitation to believe.",
        href: "/asv/john",
      },
      {
        title: "Study with the KJV",
        description: "Read in a classic translation with chapter introductions and study overlays alongside the text.",
        href: "/kjv",
      },
    ],
    whyThisFeelsDifferent: "Why This Feels Different",
    slowerDeeperStudy: "Built for slower, deeper Bible study.",
    studyFeatures: [
      {
        title: "Book introductions",
        description: "Every book opens with context, themes, and chapter-level orientation before you read.",
      },
      {
        title: "Chapter study mode",
        description: "Move between the biblical text, important verses, and guided questions without losing your place.",
      },
      {
        title: "Parallel reading",
        description: "Place study content or another translation beside the text for slower comparative study.",
      },
    ],
    translationShelf: "Translation Shelf",
    chooseReadingTradition: "Choose your reading tradition.",
    shelfLinks: [
      { label: "American Standard Version", href: "/asv", note: "English translation, public domain" },
      { label: "King James Version", href: "/kjv", note: "Historic English cadence" },
      { label: "Arabic Van Dyck", href: "/avd", note: "Trusted Arabic reading tradition" },
    ],
    beginHere: "Begin Here",
    gentlePath: "A gentle path for first-time readers.",
    gentlePathBody: "If Scripture feels large, start with a small set of decisive chapters. Read patiently, notice how each scene reveals Christ, and let the study prompts slow you down.",
    insideTheReader: "Inside The Reader",
    redesignedChapterExperience: "A redesigned chapter experience.",
    readerHighlights: [
      "Chapter reading with structural commentary and important verses close at hand.",
      "Side-by-side translation and study mode for slower comparative reading.",
      "Book introductions that orient you before you enter the text.",
    ],
    readAChapter: "Read a Chapter",
    openBookIntroduction: "Open a Book Introduction",
    hope: "Hope",
    pathToSalvation: "The Path to Salvation",
    salvationIntro: "God loves you and has a plan for your life. Follow these steps to begin your journey of faith.",
    recognizeNeed: "Recognize your need for salvation",
    believeInJesus: "Believe in Jesus Christ",
    confessRepent: "Confess and repent of your sins",
    acceptJesus: "Accept Jesus as your Lord and Savior",
    prayerForSalvation: "Prayer for Salvation",
    prayerText: "Dear God, I know that I am a sinner and need Your forgiveness. I believe that Jesus Christ died for my sins. I want to turn from my sins and follow You. I now invite Jesus to come into my heart and life as my personal Savior. I want to trust and follow You as my Lord. In Jesus' name, Amen.",
    salvationVerses: [
      "\"For all have sinned and fall short of the glory of God.\"",
      "\"For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.\"",
      "\"If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.\"",
      "\"If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved.\"",
    ],
    salvationReferences: ["Romans 3:23", "John 3:16", "1 John 1:9", "Romans 10:9"],
    community: "Community",
    churchGuidanceTitle: "Find Guidance in a Faithful Church",
    churchGuidanceIntro: "This app is a tool, not a substitute for church community.",
    importantReminder: "Important Reminder",
    churchReminderText: "This Bible study app is not a replacement for the growth and guidance you need in a discipling relationship within a healthy church context.",
    churchCommunityText: "While this app can aid your personal study, true spiritual growth happens in community. We strongly encourage you to:",
    attendChurch: "Regularly attend a Bible-believing church",
    seekMentorship: "Seek mentorship from mature believers",
    participateGroups: "Participate in small groups or Bible studies",
    worshipPrayer: "Engage in corporate worship and prayer",
    findChurchNearYou: "Find a Church Near You",
    gospelEntries: [
      { label: "Luke 1", href: "/asv/luke/1" },
      { label: "Luke 2", href: "/asv/luke/2" },
      { label: "Matthew 5", href: "/asv/matthew/5" },
      { label: "John 3", href: "/asv/john/3" },
      { label: "Mark 8", href: "/asv/mark/8" },
      { label: "Luke 15", href: "/asv/luke/15" },
      { label: "John 14", href: "/asv/john/14" },
      { label: "Luke 23", href: "/asv/luke/23" },
      { label: "Luke 24", href: "/asv/luke/24" },
      { label: "Acts 2", href: "/asv/acts/2" },
      { label: "Romans 3", href: "/asv/romans/3" },
      { label: "Romans 8", href: "/asv/romans/8" },
    ],
    gospelDescriptions: [
      "The birth of Jesus foretold and the purpose of his coming.",
      "The birth of Jesus and his early years.",
      "The Sermon on the Mount: Jesus' teachings on Kingdom living.",
      "Jesus explains the concept of being 'born again' and God's love for the world.",
      "Peter's confession of Christ and Jesus predicts his death and resurrection.",
      "Parables of the Lost Sheep, Lost Coin, and Prodigal Son, illustrating God's love for the lost.",
      "Jesus comforts his disciples and promises the Holy Spirit.",
      "The crucifixion of Jesus.",
      "The resurrection of Jesus and his appearances to disciples.",
      "The coming of the Holy Spirit and the birth of the Church.",
      "The problem of sin and the solution through faith in Christ.",
      "Life in the Spirit and God's love for believers.",
    ],
  },
  Spanish: {
    selectBook: "Seleccionar Libro",
    selectChapter: "Seleccionar Capítulo",
    search: "Buscar",
    bibleNavigation: "Navegación de la Biblia",
    selectBookOrChapter: "Seleccione un libro o capítulo para leer",
    commentary: "Comentario",
    share: "Compartir",
    shareVerse: "Compartir este versículo",
    copyLink: "Copiar enlace",
    linkCopied: "¡Enlace copiado!",
    expandSidebar: "Expandir barra lateral",
    collapseSidebar: "Contraer barra lateral",
    chapters: "Capítulos",
    books: "Libros",
    study: "Estudio",
    questions: "Preguntas",
    sections: "Secciones",
    onThisPage: "En esta página",
    introduction: "Introducción",
    oldTestament: "Antiguo Testamento",
    newTestament: "Nuevo Testamento",
    home: "Inicio",
    bookIntroduction: "Introducción del Libro",
    overview: "Resumen",
    currentEdition: "Edición Actual",
    translationLibrary: "Biblioteca de Traducciones",
    browseScripture: "Explora la Escritura por",
    testamentBookChapter: "testamento, libro y capítulo",
    translationLibraryDesc: "Pasa del contexto de la traducción a un libro específico sin salir del ambiente de estudio.",
    published: "Publicado",
    enterTheText: "Entrar al texto.",
    majorMovementsIn: "Grandes movimientos en",
    startWithIntroduction: "Comienza con la introducción o entra al libro capítulo por capítulo.",
    fullChapterGridContinues: "La cuadrícula completa de capítulos continúa abajo.",
    chapterReading: "Lectura del Capítulo",
    chapterReadingDesc: "Lee el texto, resalta versículos importantes y recorre el comentario sin salir del capítulo.",
    previousChapter: "Capítulo anterior",
    nextChapter: "Capítulo siguiente",
    showSidebar: "Mostrar barra lateral",
    menu: "Menú",
    sectionLabel: "Sección",
    chapterLabel: "Capítulo",
    ofLabel: "de",
    sideBySide: "Lado a lado",
    verseByVerse: "Versículo por versículo",
    askBibleQuestion: "Haz una pregunta bíblica",
    navigationMenu: "Menú de navegación",
    holyBibleReader: "Lector de la Santa Biblia",
    illuminatedStudy: "Estudio Iluminado",
    library: "Biblioteca",
    ask: "Preguntar",
    scriptureContextReverence: "Escritura, Contexto, Reverencia",
    homeHeroTitleStart: "Lee la Biblia en una",
    homeHeroTitleAccent: "sala de estudio moderna,",
    homeHeroTitleEnd: "no en un panel utilitario.",
    homeHeroBody: "Pasa de introducciones de libros a la lectura por capítulos, estudio lado a lado, preguntas guiadas y acceso multilingüe en una sola experiencia.",
    openStudyLibrary: "Abrir la Biblioteca de Estudio",
    readingPathsTitle: "Rutas de lectura",
    readingPaths: [
      {
        title: "Comienza con Génesis",
        description: "Entra en el mundo narrativo de la Escritura con la creación, el pacto y la forma de la redención.",
        href: "/asv/genesis",
      },
      {
        title: "Conoce a Cristo en Juan",
        description: "Comienza con un Evangelio que se detiene en la identidad, las señales y la invitación a creer.",
        href: "/asv/john",
      },
      {
        title: "Estudia con la KJV",
        description: "Lee en una traducción clásica con introducciones por capítulo y capas de estudio junto al texto.",
        href: "/kjv",
      },
    ],
    whyThisFeelsDifferent: "Por qué se siente diferente",
    slowerDeeperStudy: "Hecho para un estudio bíblico más lento y profundo.",
    studyFeatures: [
      {
        title: "Introducciones de libros",
        description: "Cada libro comienza con contexto, temas y orientación por capítulos antes de leer.",
      },
      {
        title: "Modo de estudio por capítulo",
        description: "Muévete entre el texto bíblico, versículos importantes y preguntas guiadas sin perder tu lugar.",
      },
      {
        title: "Lectura paralela",
        description: "Coloca contenido de estudio u otra traducción junto al texto para una lectura comparativa más pausada.",
      },
    ],
    translationShelf: "Estante de traducciones",
    chooseReadingTradition: "Elige tu tradición de lectura.",
    shelfLinks: [
      { label: "American Standard Version", href: "/asv", note: "Traducción inglesa, dominio público" },
      { label: "King James Version", href: "/kjv", note: "Cadencia histórica del inglés" },
      { label: "Arabic Van Dyck", href: "/avd", note: "Tradición confiable de lectura en árabe" },
    ],
    beginHere: "Empieza aquí",
    gentlePath: "Un camino amable para quienes comienzan.",
    gentlePathBody: "Si la Escritura parece extensa, empieza con un pequeño grupo de capítulos decisivos. Lee con paciencia, observa cómo cada escena revela a Cristo y deja que las preguntas de estudio marquen el ritmo.",
    insideTheReader: "Dentro del lector",
    redesignedChapterExperience: "Una experiencia de capítulo rediseñada.",
    readerHighlights: [
      "Lectura por capítulo con comentario estructural y versículos importantes al alcance.",
      "Modo de traducción y estudio lado a lado para una lectura comparativa más pausada.",
      "Introducciones de libros que te orientan antes de entrar al texto.",
    ],
    readAChapter: "Leer un capítulo",
    openBookIntroduction: "Abrir una introducción del libro",
    hope: "Esperanza",
    pathToSalvation: "El Camino de la Salvación",
    salvationIntro: "Dios te ama y tiene un plan para tu vida. Sigue estos pasos para comenzar tu camino de fe.",
    recognizeNeed: "Reconoce tu necesidad de salvación",
    believeInJesus: "Cree en Jesucristo",
    confessRepent: "Confiesa y arrepiéntete de tus pecados",
    acceptJesus: "Acepta a Jesús como tu Señor y Salvador",
    prayerForSalvation: "Oración de Salvación",
    prayerText: "Querido Dios, sé que soy pecador y necesito Tu perdón. Creo que Jesucristo murió por mis pecados. Quiero apartarme de mis pecados y seguirte. Ahora invito a Jesús a entrar en mi corazón y en mi vida como mi Salvador personal. Quiero confiar en Ti y seguirte como mi Señor. En el nombre de Jesús, amén.",
    salvationVerses: [
      "\"Porque todos pecaron y están destituidos de la gloria de Dios.\"",
      "\"Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree no se pierda, mas tenga vida eterna.\"",
      "\"Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados y limpiarnos de toda maldad.\"",
      "\"Si confiesas con tu boca que Jesús es el Señor y crees en tu corazón que Dios lo levantó de los muertos, serás salvo.\"",
    ],
    salvationReferences: ["Romanos 3:23", "Juan 3:16", "1 Juan 1:9", "Romanos 10:9"],
    community: "Comunidad",
    churchGuidanceTitle: "Encuentra Guía en una Iglesia Fiel",
    churchGuidanceIntro: "Esta aplicación es una herramienta, no un sustituto de la comunidad de la iglesia.",
    importantReminder: "Recordatorio Importante",
    churchReminderText: "Esta aplicación de estudio bíblico no reemplaza el crecimiento y la guía que necesitas dentro de una relación de discipulado en el contexto de una iglesia saludable.",
    churchCommunityText: "Aunque esta aplicación puede ayudar a tu estudio personal, el verdadero crecimiento espiritual ocurre en comunidad. Te animamos a:",
    attendChurch: "Asistir regularmente a una iglesia que crea en la Biblia",
    seekMentorship: "Buscar mentoría de creyentes maduros",
    participateGroups: "Participar en grupos pequeños o estudios bíblicos",
    worshipPrayer: "Participar en adoración y oración congregacional",
    findChurchNearYou: "Encuentra una iglesia cercana",
    gospelEntries: [
      { label: "Lucas 1", href: "/asv/luke/1" },
      { label: "Lucas 2", href: "/asv/luke/2" },
      { label: "Mateo 5", href: "/asv/matthew/5" },
      { label: "Juan 3", href: "/asv/john/3" },
      { label: "Marcos 8", href: "/asv/mark/8" },
      { label: "Lucas 15", href: "/asv/luke/15" },
      { label: "Juan 14", href: "/asv/john/14" },
      { label: "Lucas 23", href: "/asv/luke/23" },
      { label: "Lucas 24", href: "/asv/luke/24" },
      { label: "Hechos 2", href: "/asv/acts/2" },
      { label: "Romanos 3", href: "/asv/romans/3" },
      { label: "Romanos 8", href: "/asv/romans/8" },
    ],
    gospelDescriptions: [
      "El nacimiento de Jesús anunciado de antemano y el propósito de su venida.",
      "El nacimiento de Jesús y sus primeros años.",
      "El Sermón del Monte: las enseñanzas de Jesús sobre la vida del Reino.",
      "Jesús explica el concepto de 'nacer de nuevo' y el amor de Dios por el mundo.",
      "La confesión de Pedro sobre Cristo y Jesús predice su muerte y resurrección.",
      "Parábolas de la oveja perdida, la moneda perdida y el hijo pródigo, que ilustran el amor de Dios por los perdidos.",
      "Jesús consuela a sus discípulos y promete al Espíritu Santo.",
      "La crucifixión de Jesús.",
      "La resurrección de Jesús y sus apariciones a los discípulos.",
      "La venida del Espíritu Santo y el nacimiento de la Iglesia.",
      "El problema del pecado y la solución por medio de la fe en Cristo.",
      "La vida en el Espíritu y el amor de Dios por los creyentes.",
    ],
  },
  Arabic: {
    selectBook: "اختر الكتاب",
    selectChapter: "اختر الفصل",
    search: "بحث",
    bibleNavigation: "تنقل الكتاب المقدس",
    selectBookOrChapter: "اختر كتابًا أو فصلًا للقراءة",
    commentary: "تعليق",
    share: "شارك",
    shareVerse: "شارك هذه الآية",
    copyLink: "نسخ الرابط",
    linkCopied: "تم نسخ الرابط!",
    expandSidebar: "توسيع الشريط الجانبي",
    collapseSidebar: "طي الشريط الجانبي",
    chapters: "الاصحاحات",
    books: "الكتب",
    study: "دراسة",
    questions: "أسئلة",
    sections: "أقسام",
    onThisPage: "في هذه الصفحة",
    introduction: "مقدمة",
    oldTestament: "العهد القديم",
    newTestament: "العهد الجديد",
    home: "الرئيسية",
    bookIntroduction: "مقدمة السفر",
    overview: "نظرة عامة",
    currentEdition: "النسخة الحالية",
    translationLibrary: "مكتبة الترجمات",
    browseScripture: "تصفح الكتاب المقدس حسب",
    testamentBookChapter: "العهد والسفر والإصحاح",
    translationLibraryDesc: "انتقل من سياق الترجمة إلى سفر محدد دون مغادرة أجواء الدراسة.",
    published: "نُشر",
    enterTheText: "ادخل إلى النص.",
    majorMovementsIn: "الحركات الرئيسية في",
    startWithIntroduction: "ابدأ بالمقدمة أو ادخل إلى السفر إصحاحًا بعد إصحاح.",
    fullChapterGridContinues: "تكمل شبكة الإصحاحات الكاملة بالأسفل.",
    chapterReading: "قراءة الإصحاح",
    chapterReadingDesc: "اقرأ النص، وأبرز الآيات المهمة، وانتقل عبر الشرح دون مغادرة الإصحاح.",
    previousChapter: "الإصحاح السابق",
    nextChapter: "الإصحاح التالي",
    showSidebar: "إظهار الشريط الجانبي",
    menu: "القائمة",
    sectionLabel: "قسم",
    chapterLabel: "الإصحاح",
    ofLabel: "من",
    sideBySide: "جنبًا إلى جنب",
    verseByVerse: "آية بآية",
    askBibleQuestion: "اسأل سؤالًا كتابيًا",
    navigationMenu: "قائمة التنقل",
    holyBibleReader: "قارئ الكتاب المقدس",
    illuminatedStudy: "دراسة مضيئة",
    library: "المكتبة",
    ask: "اسأل",
    scriptureContextReverence: "الكتاب، والسياق، والوقار",
    homeHeroTitleStart: "اقرأ الكتاب المقدس في",
    homeHeroTitleAccent: "غرفة دراسة حديثة،",
    homeHeroTitleEnd: "لا في لوحة أدوات جامدة.",
    homeHeroBody: "انتقل من مقدمات الأسفار إلى قراءة الإصحاحات، والدراسة جنبًا إلى جنب، والأسئلة الموجَّهة، والوصول متعدد اللغات في تجربة واحدة متكاملة.",
    openStudyLibrary: "افتح مكتبة الدراسة",
    readingPathsTitle: "مسارات القراءة",
    readingPaths: [
      {
        title: "ابدأ بسفر التكوين",
        description: "ادخل إلى عالم القصة الكتابية من خلال الخلق والعهد وشكل الفداء.",
        href: "/avd/genesis",
      },
      {
        title: "تعرف إلى المسيح في يوحنا",
        description: "ابدأ بإنجيل يتأمل في الهوية والآيات والدعوة إلى الإيمان.",
        href: "/avd/john",
      },
      {
        title: "ادرس مع فاندايك",
        description: "اقرأ في ترجمة عربية موثوقة مع مقدمات الإصحاحات وطبقات الدراسة إلى جانب النص.",
        href: "/avd",
      },
    ],
    whyThisFeelsDifferent: "لماذا يبدو مختلفًا",
    slowerDeeperStudy: "مصمم لدراسة كتابية أبطأ وأعمق.",
    studyFeatures: [
      {
        title: "مقدمات للأسفار",
        description: "يبدأ كل سفر بخلفية وموضوعات وتمهيد على مستوى الإصحاحات قبل أن تبدأ القراءة.",
      },
      {
        title: "وضع دراسة الإصحاح",
        description: "انتقل بين النص الكتابي والآيات المهمة والأسئلة الموجَّهة دون أن تفقد موضعك.",
      },
      {
        title: "قراءة متوازية",
        description: "ضع محتوى الدراسة أو ترجمة أخرى بجانب النص لقراءة مقارنة أكثر هدوءًا.",
      },
    ],
    translationShelf: "رف الترجمات",
    chooseReadingTradition: "اختر تقليدك القرائي.",
    shelfLinks: [
      { label: "الترجمة العربية فاندايك", href: "/avd", note: "تقليد عربي موثوق للقراءة" },
      { label: "النسخة الأمريكية القياسية", href: "/asv", note: "ترجمة إنجليزية ضمن الملكية العامة" },
      { label: "نسخة الملك جيمس", href: "/kjv", note: "صياغة إنجليزية كلاسيكية" },
    ],
    beginHere: "ابدأ هنا",
    gentlePath: "مسار هادئ للمبتدئين.",
    gentlePathBody: "إذا بدا لك الكتاب واسعًا، فابدأ بمجموعة صغيرة من الإصحاحات الحاسمة. اقرأ بهدوء، ولاحظ كيف يكشف كل مشهد عن المسيح، ودع أسئلة الدراسة تُبطئ إيقاعك.",
    insideTheReader: "داخل القارئ",
    redesignedChapterExperience: "تجربة إصحاح معاد تصميمها.",
    readerHighlights: [
      "قراءة الإصحاح مع شرح بنيوي وآيات مهمة قريبة منك.",
      "وضع الترجمة والدراسة جنبًا إلى جنب لقراءة مقارنة أكثر تأنّيًا.",
      "مقدمات للأسفار تهيئك قبل الدخول إلى النص.",
    ],
    readAChapter: "اقرأ إصحاحًا",
    openBookIntroduction: "افتح مقدمة السفر",
    hope: "رجاء",
    pathToSalvation: "طريق الخلاص",
    salvationIntro: "الله يحبك وله خطة لحياتك. اتبع هذه الخطوات لتبدأ رحلة الإيمان.",
    recognizeNeed: "اعترف باحتياجك إلى الخلاص",
    believeInJesus: "آمن بيسوع المسيح",
    confessRepent: "اعترف بخطاياك وتب عنها",
    acceptJesus: "اقبل يسوع ربًا ومخلصًا لك",
    prayerForSalvation: "صلاة للخلاص",
    prayerText: "يا الله، أنا أعلم أنني خاطئ وأحتاج إلى غفرانك. أؤمن أن يسوع المسيح مات من أجل خطاياي. أريد أن أترك خطاياي وأتبعك. الآن أدعو يسوع أن يدخل إلى قلبي وحياتي كمخلصي الشخصي. أريد أن أثق بك وأتبعك ربًا لحياتي. باسم يسوع، آمين.",
    salvationVerses: [
      "\"إذ الجميع أخطأوا وأعوزهم مجد الله.\"",
      "\"لأنه هكذا أحب الله العالم حتى بذل ابنه الوحيد، لكي لا يهلك كل من يؤمن به بل تكون له الحياة الأبدية.\"",
      "\"إن اعترفنا بخطايانا فهو أمين وعادل، حتى يغفر لنا خطايانا ويطهرنا من كل إثم.\"",
      "\"لأنك إن اعترفت بفمك بالرب يسوع، وآمنت بقلبك أن الله أقامه من الأموات، خَلَصت.\"",
    ],
    salvationReferences: ["رومية 3:23", "يوحنا 3:16", "1 يوحنا 1:9", "رومية 10:9"],
    community: "الجماعة",
    churchGuidanceTitle: "ابحث عن إرشاد في كنيسة أمينة",
    churchGuidanceIntro: "هذا التطبيق أداة، وليس بديلًا عن حياة الكنيسة.",
    importantReminder: "تذكير مهم",
    churchReminderText: "تطبيق دراسة الكتاب المقدس هذا ليس بديلًا عن النمو والإرشاد اللذين تحتاجهما في علاقة تلمذة داخل سياق كنيسة سليمة.",
    churchCommunityText: "مع أن هذا التطبيق قد يساعد في دراستك الشخصية، إلا أن النمو الروحي الحقيقي يحدث في الجماعة. نحن نشجعك على:",
    attendChurch: "الانتظام في حضور كنيسة تؤمن بالكتاب المقدس",
    seekMentorship: "طلب الإرشاد من مؤمنين ناضجين",
    participateGroups: "المشاركة في مجموعات صغيرة أو دراسات كتابية",
    worshipPrayer: "الاشتراك في العبادة الجماعية والصلاة",
    findChurchNearYou: "ابحث عن كنيسة قريبة",
    gospelEntries: [
      { label: "لوقا 1", href: "/avd/luke/1" },
      { label: "لوقا 2", href: "/avd/luke/2" },
      { label: "متى 5", href: "/avd/matthew/5" },
      { label: "يوحنا 3", href: "/avd/john/3" },
      { label: "مرقس 8", href: "/avd/mark/8" },
      { label: "لوقا 15", href: "/avd/luke/15" },
      { label: "يوحنا 14", href: "/avd/john/14" },
      { label: "لوقا 23", href: "/avd/luke/23" },
      { label: "لوقا 24", href: "/avd/luke/24" },
      { label: "أعمال 2", href: "/avd/acts/2" },
      { label: "رومية 3", href: "/avd/romans/3" },
      { label: "رومية 8", href: "/avd/romans/8" },
    ],
    gospelDescriptions: [
      "البشارة بميلاد يسوع والغاية من مجيئه.",
      "ميلاد يسوع وسنواته الأولى.",
      "العظة على الجبل: تعاليم يسوع عن حياة الملكوت.",
      "يشرح يسوع مفهوم الولادة الجديدة ومحبة الله للعالم.",
      "اعتراف بطرس بالمسيح وإعلان يسوع عن موته وقيامته.",
      "أمثال الخروف الضال والدرهم المفقود والابن الضال، التي تُظهر محبة الله للضالين.",
      "يسوع يعزي تلاميذه ويعدهم بالروح القدس.",
      "صلب يسوع.",
      "قيامة يسوع وظهوره لتلاميذه.",
      "حلول الروح القدس وولادة الكنيسة.",
      "مشكلة الخطية والحل بالإيمان بالمسيح.",
      "الحياة في الروح ومحبة الله للمؤمنين.",
    ],
  },
};
